version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: Test
          command: npm run test
  semantic_release:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: release to GitHub
          command: npx semantic-release
      - run:
          name: Push Code to Bitbucket
          # should fix "remote branch is behind local"
          command: git push https://viewar_sf:${BB_APP_PW}@bitbucket.org/viewar_sf/eslint-config-viewar.git
      - run:
          name: Push tags to Bitbucket
          command: git push https://viewar_sf:${BB_APP_PW}@bitbucket.org/viewar_sf/eslint-config-viewar.git --tags

workflows:
  version: 2
  lint_and_release:
    jobs:
      - test
      - semantic_release:
          requires:
            - test
          filters:
            branches:
              only: master
